# Generated by Django 5.0.7 on 2026-06-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_rename_stock_libro_vendido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='libro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
